apiVersion: v1
description: Rabbitmq metrics exporter for prometheus
name: prometheus-rabbitmq-exporter
version: 0.5.6
appVersion: v0.29.1
home: https://github.com/kbudde/rabbitmq_exporter
sources:
- https://github.com/kbudde/rabbitmq_exporter
maintainers:
- name: juanchimienti
  email: juan.chimienti@gmail.com
